// Based on the team's analogy brief and Jongchan's revised board/support example.
// This is a teaching design contract, not a transcript of hidden CustomGPT settings.
export const ANALOGY_DESIGN_RULES = `ANALOGY DESIGN BEFORE WORDING:
Return analogyPlan first, then write the five slides and image plans from it in the SAME response. This is a concise teacher-reviewable design, not a chain-of-thought transcript. Choose ONE useful relationship at entities, configurations OR mechanisms depth; never require all three. Explain what makes the target hard to picture, why this familiar experience is accessible in the supplied classroom context, one supplied correspondence, and one meaningful correspondence/relation still left for students.
Select the changed input and prediction ONLY AFTER choosing that shared relationship. predictionSupport must say how the relation actually helps with predictionFocus without an unstated law or prerequisite. An accounting analogy can support where an amount is stored/transferred or whether the total changes; it cannot on its own justify mass versus cart speed, force magnitude, acceleration, or the microscopic mechanism. Never force a conspicuous added mass or a coasting-speed question onto an unrelated analogy. If the inference is unsupported, change the analogue OR the comparison; do not paper over it with a limitation.
Jongchan's revised example uses people simultaneously supporting a loaded board to ground load paths in a truss. It names board and hands/supports, compares the SAME truss with a moved load, returns to the same pair, and ends with a student's question. Transfer that clarity and dependency between steps, not the grade-10 engineering topic into every physics lesson.
STEP 1: name BOTH the target concept/concrete scientific situation AND the familiar concept/situation in natural student language from the outset. The app displays the learning target plus the SAME familiar and target pictures used on steps 2 and 4, with separate familiar/science headings and named captions. Use a concrete learning question or comparison purpose in the title rather than a generic label such as Two Starting Scenes. In one short body, introduce both situations and the target's hard-to-picture question so learners understand why they will compare them. Then give one concrete notice/point/draw task that attends to an observable feature relevant to the chosen sharedRelation, such as an amount, support or transfer. This should prepare the next mapping step without requiring an unsupported mapping; do not merely inventory unrelated objects or their positions. A topic banner or a familiar scene alone is insufficient. Reserve the first concrete mappingHint and responseStarter for step 2; do not give the completed correspondence or predicted answer here. A learner unfamiliar with the familiar scene should have enough literal context to imagine it. Do not assume an experience or prior law without classroom evidence. For a transfer task, specify its starting and finishing moments; if the pictured hand already holds counters, do not imply its source tray will lose them again when the hand reaches the receiving tray. Count in-transit objects when discussing a total.
STEP 2: continue from the SAME named pair and open question on step 1; focus the already introduced scientific setup on the relevant hidden aspect instead of restarting the story. The app shows familiar/science headings and renders analogyPlan.mappingHint and analogyPlan.responseStarter on the STUDENT canvas. mappingHint (at most 20 words/140 characters) must supply ONE defensible foothold connecting named visible source and target features; it may give that first correspondence. responseStarter (at most 12 words/100 characters) is an incomplete sentence with a blank or ellipsis, anchored to the remaining correspondence. The task names the concrete parts/relationship to compare and asks learners to complete a DIFFERENT, useful relation, never repeat the providedMapping. Do not leave the only foothold in private notes. Do not duplicate the hint/starter in body/task.
STEP 3: show baseline and variation of the SAME scientific system, one input change only, and ask learners to write/draw a prediction with one reason that uses the chosen relation. Say exactly what they should predict and at what moment, using everyday wording such as 'when the spring returns to its normal length' rather than an unexplained technical endpoint. Supply an unfamiliar target fact needed for reasoning as context, but leave the requested conclusion open. Pictures show starting conditions only. Fixed conditions must be physically consistent: shortening a spring between a fixed anchor and contacting cart requires the cart (and any explicitly planned rigid connector) to move toward the anchor; this linked movement is not an additional independent input. Prefer the simplest target apparatus that makes the relation visible. For a qualitative spring/cart opening, a spring attached to a fixed wall and touching the cart directly is sufficient; omit extra plungers, shafts and latch mechanisms unless they are instructionally necessary. Keep any required rigid connector the same length across conditions.
STEP 4: return to the SAME familiar/target pair; ask learners to support or reconsider their earlier prediction using a named shared relationship. This must follow from step 2 and step 3. boundaryDecision normally omit, stage reflect. Include a boundary only when simple, consequential and clarifying; if confusing, rewrite it or omit it. It is not a mandatory exercise and cannot rescue a flawed core analogy.
STEP 5: briefly recall the open comparison and bridge to the lesson, then ask learners to write their OWN target question on the question card. No invented observations, finished question to copy, or new scenario.
Keep the student action concrete and the language accessible. Private notes identify what reasoning to listen for and an actionable follow-up if the learner is stuck. All plan fields EXCEPT mappingHint and responseStarter are PRIVATE. The public hint/starter must not contain private answers, strategy jargon, or a completed prediction.`;

export const ANALOGY_REVIEW_RULES = `ANALOGY DEPENDENCY REVIEW:
Compare the actual slides with analogyPlan; do not assume the plan is correct because it is structured. Check paired opening with BOTH named concepts and a plain reason to compare -> supplied visible foothold -> remaining learner inference -> supported comparison/prediction -> reflection -> own question. Slide 1 displays the same familiar and target pictures as slides 2 and 4, plus the learning-target banner. Its student text must introduce both named situations and a simple target question/purpose; a familiar-only body with a generic target banner is insufficient. Check that slide 2 continues this pair and purpose, without renaming or introducing an unrelated system. Naming both situations and showing the target from the outset is required, not answer leakage; reserve the first concrete supplied correspondence for slide 2.
Flag a definite unsupported transfer even when every isolated sentence is scientifically possible: counter/tray accounting used to justify which mass makes a cart faster is a failure unless the missing relationship is explicitly established at the learner's level. Quote the prediction/reflection task and request a different supported comparison or analogue, not a cosmetic disclaimer. A change in a conserved amount or its distribution can be supported by accounting and is not automatically a failure.
The app renders mappingHint and responseStarter on slide 2 alongside the two pictures. They count as student-facing content. Confirm the hint provides a concrete correspondence, the task leaves a different meaningful inference open, and all required referents/facts are visible or plainly introduced. If the only route to answering is hidden in teacher notes or an unknown prerequisite, quote the task and request a small visible foothold. One supplied mapping is permitted and is NOT premature answer leakage; giving every requested relation is.
Check sharedRelation, predictionSupport and student wording agree. Review boundaryDecision against slide 4: omitted boundaries are complete; confusing ones should be simplified or removed. Do not invent generic caveats. Check that student scaffold edits still match the pictures and task. These are required instructional dependencies, not optional stylistic polish. Report only concrete failures with a quoted editable field; do not demand a perfect analogy or a full lesson explanation.`;

export const REFERENCE_STORY_DESIGN_RULES = `REFERENCE-STORY ANALOGY DESIGN:
Use the original team's target -> familiar analogue -> guided mapping -> useful consolidation/optional probing -> learner question sequence. Return analogyPlan first, then the five slides and TWO image plans from that design in the SAME response. Plan the targetDifficulty, familiarExperience, ONE depth (entities, configurations OR mechanisms), sharedRelation, providedMapping, openMapping, boundaryDecision and boundaryReason. mappingHint and responseStarter are the only public plan fields. There are no changedInput, fixedConditions, predictionFocus or predictionSupport fields in this method.
Choose a familiar process whose actual relationship helps with the target difficulty. Prefer a simple accurate relation over a superficial theme match. State the relevant prior knowledge in context when learners need it; do not assume a law or unfamiliar experience. An amounts/accounting comparison supports tracking amounts and transfers, not inferring a mass-speed relationship on its own. Repair a faulty core relation by choosing a better familiar situation or a smaller supported inference, not a complicated disclaimer.
Choose ONE open correspondence small enough for these learners to complete in a brief opening; do not try to cover the entire curriculum objective. Add a target subsystem or scientific concept only when it is essential to that correspondence and students have visible support for the connection. Naming several destinations or technical terms is not itself that support. Use an exact pictured count only when counting is instructionally necessary; an uncomplicated qualitative relation can be sufficient. A boundary must address an overextension invited by this actual mapping or task, not list unrelated things the comparison cannot explain.
STEP 1 target: name BOTH the target concept/concrete science situation AND the familiar concept/situation. The app displays the learning target and BOTH separate pictures with their named captions. Lead with a plain target-focused question or difficulty and say why the familiar comparison may help. Use a concrete title that communicates that purpose. Ask for an initial idea or relevant noticing, leaving the scientific explanation and the first supplied correspondence open. This paired opening is the teacher's explicit adaptation of the original target-first step.
STEP 2 analogue: activate the SAME familiar process introduced on step 1 ON ITS OWN. Only its familiar picture appears. Name the literal objects and action in plain language; invite students to recall, imagine, point to or describe the relevant familiar relation. Attend to amounts, support or transfer when that is the chosen relation, not unrelated inventory. Do not supply the target correspondence here or require learners to invent it unaided. For a transfer, specify the start and end moments; count in-transit objects in a total and never make a source lose items twice.
STEP 3 mapping: bring the SAME familiar and scientific pictures together and connect their previously introduced features at the chosen depth. The app renders mappingHint (at most 20 words/140 characters) and responseStarter (at most 12 words/100 characters) on this page. Supply ONE concrete defensible correspondence in mappingHint, then leave a DIFFERENT meaningful relation or extension in openMapping for learners to complete. The incomplete starter contains a blank or ellipsis and supports that remaining inference. Name the referents in the task and give any small factual foothold needed; do not leave it only in private notes. Do not duplicate the hint/starter in body or task.
STEP 4 reflect by default: revisit the SAME pair to consolidate, explain or check the usefulness of the shared relationship, with one concrete learner response. Optional probing may clarify a question that actually arises from this mapping. It does not require a new target condition, a variation picture or a separate controlled-comparison exercise. Choose stage limits only for one simple consequential boundary that prevents a likely misunderstanding. If the boundary distracts or confuses, rewrite or omit it and use reflect. A useful consolidation without limits is complete.
STEP 5 question: briefly connect the still-open target difficulty to the lesson and ask students to WRITE their OWN scientific target question to hand in. The app supplies the blank MY QUESTION card and incomplete starters. Do not provide a finished question to copy, invent an observed outcome or switch to a new scenario.
Keep exactly one central student action on each page, simple wording and stable object names/images across the story. Private notes state purpose, reasoning to listen for and an actionable follow-up if stuck; they must not substitute for necessary student-visible support. All plan fields except mappingHint and responseStarter remain private.`;

export const REFERENCE_STORY_REVIEW_RULES = `REFERENCE-STORY DEPENDENCY REVIEW:
Compare the actual student story and analogyPlan against the selected target -> familiar activation -> guided mapping -> consolidation/optional boundary -> own-question sequence. Page 1 must name both situations, show their paired context and give a plain target question/purpose; a familiar-only body plus a generic target banner is insufficient. Page 2 then activates the same familiar process on its own, without a solved target correspondence. Page 3 supplies one concrete mapping foothold and leaves a different meaningful relation for the learner. Page 4 consolidates that relation or probes one useful uncertainty; page 5 returns to the learner's own target question.
The app renders mappingHint and responseStarter on slide 3 beside the stable familiar/target pair. These count as student-facing support. Check that their named features exist in the pictures and that the task leaves a useful inference open, rather than asking the learner to copy the supplied mapping. A small supplied correspondence is permitted here; giving every requested relation is not. Naming both situations and showing the scientific picture on slide 1 is required and is not answer leakage.
Check targetDifficulty, familiarExperience, sharedRelation, providedMapping and openMapping against the actual fields; structured planning is not automatically correct. Flag a definite unsupported inference, misleading relation, missing prerequisite or absent student foothold with an exact editable quote. Do not ask for changedInput, fixedConditions, predictionFocus, predictionSupport, a variation image or a controlled prediction stage: those belong to the other story method. A reference story is complete without them.
Check that the open correspondence is achievable from the supplied learner context and student-visible support. A list of newly named target subsystems does not establish how they connect to the familiar process. If a task requires that unstated connection, identify the missing foothold or narrow the inference; do not demand that the brief opening explain the full lesson. A boundary introducing a new scientific topic solely to deny that the comparison explains it should be removed when it does not clarify an overextension invited by this mapping.
Review boundaryDecision against slide 4. Omitted boundaries are complete. A limits page must prevent a concrete likely misunderstanding; simplify or omit a confusing boundary rather than inventing a generic caveat. Do not demand a perfect analogy, all mapping depths or a full lesson explanation. Only report concrete scientific/method failures, not optional stylistic polishing.`;

export const SIX_STEP_DESIGN_RULES = `SAMANEH SIX-STEP ANALOGY DESIGN — TEACHER-LED DISCUSSION:
Return analogyPlan first, then the complete student slides, separate teacherNotes and three image plans. Choose ONE useful scientific relationship and ONE mapping depth: entities, configurations OR mechanisms. This is a brief engagement opening, not the whole lesson. Keep the scientific target and familiar source distinct.
LESSON-CONTEXT CLARIFICATION: Authentic means scientifically real and grounded in a real-world context; it does not require students' everyday experience. This supersedes the older source's everyday/familiar-phenomenon restriction. Choose for the specific lesson relationship and story, not familiarity alone. A natural, scientific or engineering event may be unfamiliar to these learners. Do not invent a named incident, measurement or learner experience to establish authenticity. An illustration represents the event; it is not measured evidence. Classroom location alone neither qualifies nor disqualifies a phenomenon. A contrived apparatus does not become relevant merely because its objects are familiar.
ACCESSIBLE, FAITHFUL CONTEXT: Among scientifically suitable events, prefer one that needs little background for this brief opening; unfamiliarity is permitted, not a goal. Introduce only essential terms. Do not expose or invent an internal mechanism just to make the mapping visible. For complex hardware, show a faithful external event with a stable housing/hinge and explain a supported hidden component verbally in teacherNotes; do not invent visible spring linkages. Distinguish what students can observe from supplied background. Any depicted linkage must keep the same attachment locations on its body and moving part across moments.
PLAN: targetPhenomenon identifies one authentic real-world event and its concrete setting/action; authenticityRationale explains its real-world basis, exact lesson relationship, and the minimal context these learners need. A curriculum example is context, not a compulsory opening apparatus. A spring-loaded door may suit stored-energy release, but is only one option. Page 1 supplies enough literal setting to understand who/what is involved and what is visible; private notes explain unfamiliar terms or background without resolving the target difficulty. Never assume students personally encountered the event. Do not substitute braking/dissipation for energy storage/release merely because both involve energy. targetDifficulty names the hidden aspect of this SAME event. familiarExperience supplies an accessible relation; sharedRelation states its scientific fit. providedMapping is a PRIVATE possible correspondence for the teacher, NOT a printed foothold. openMapping and discussionGoal identify what students should discuss. applicationMode is explain OR predict; applicationSupport identifies the accessible evidence and teacher-led support needed. Keep mappingHint empty. responseStarter is optional, incomplete, at most 12 words/100 characters, with no supplied correspondence.
STUDENT / TEACHER BOUNDARY: Student titles describe a literal situation or ask an accessible question. Do not use teacher-purpose headings such as 'Connect Sources and Receivers' or 'Account for the Source'. Student fields support observation, comparison, reasoning and question generation. Body may be empty when the image and task suffice; optional captions name literal objects only. Never print category labels such as 'Familiar situation' or 'Science situation'. TeacherNotes contain two private entries: (1) purpose and reasoning to listen for; (2) practical facilitation, possible responses/correspondences, a follow-up if stuck, any necessary prerequisite and spoken transition. Each entry may use up to 150 words/900 characters; be concise but actionable. Explanations belong here, not on the student canvas. Do not merely tell the teacher to facilitate without saying how.
STEP 1 phenomenon: show an authentic real-world TARGET event closely aligned with the specific lesson, with one observation task. It need not come from students' everyday lives. Establish the concrete context and an observable feature that naturally leads to the hidden target on page 2; do not start with a disconnected spectacle or a decorative scenario. Show ONLY the phenomenon picture and the app's neutral learning-target line. No familiar analogue, comparison or scientific explanation yet. A still frame supports noticing visible features; do not call it a video or experimental evidence. If a visible change is essential, explicitly plan two ordered moments of the SAME event, not an unexplained composite. Match the question to the exact pictured interval: if the first frame is held BEFORE release and the second AFTER release, never describe both as after release. Do not ask students to see invisible energy. Use a natural title and just enough literal context to understand the event.
STEP 2 target: direct attention to the hidden or difficult-to-picture aspect of that SAME target event. Invite initial thinking without answering the question. The target picture is edited from the phenomenon image, preserving object identity, mechanism, relevant contacts and conditions. For a two-moment phenomenon, select one relevant moment. No new apparatus, invented cutaway, solved energy arrows or familiar-source props. The familiar analogue is still absent from student wording and imagery.
STEP 3 analogue: introduce the familiar source ON ITS OWN. Give enough plain context to recall or imagine its process; activate the relation useful for the target without stating a scientific correspondence. For transfers, specify a coherent start and end interval, account for anything in transit, and do not count items twice. Preserve transferred items' identity and appearance. Require exact visible counts only when instructionally necessary. Avoid an unfamiliar elaborate process or decorative similarity.
STEP 4 mapping: show the SAME familiar and target pictures together for the first time. Teacher-led mapping means the student slide presents ONE focused comparison QUESTION, with an optional incomplete responseStarter. No supplied correspondence or target explanation in its title, body, captions or starter, even if it is not the exact answer to the task. For example, both 'A compressed spring stores energy and can transfer some while expanding' and 'The tray supplying counters is like the compressed spring supplying energy' belong in PRIVATE teacherNotes. Body is usually empty here. Name concrete visible parts in the question so novices know where to start, but do not solve their relation. In notes, specify possible correspondences at the chosen depth, what to ask first, a follow-up, and any prerequisite the teacher should introduce verbally. Private guidance may contain correct answers; it need not be repeated on the student slide. Check ALL student-facing fields together for direct or paraphrased answers.
STEP 5 apply: ask students to use the correspondences discussed on page 4 to propose a tentative explanation OR supported prediction about the SAME target, with one reason. Refer to the class's proposed comparison without printing a completed mapping or scientific explanation. Do not require a new apparatus, unavailable evidence or an unstated law. A counter-accounting relation can support tracking amounts and transfers, but not on its own a mass-speed, force or microscopic mechanism claim. For a source/receiver analogy, ask explicitly where energy may come from, where it may go, or how its distribution could change. Do not ask generally HOW or WHY motion starts: that can demand a force/torque mechanism the accounting relation does not establish. If prediction requires unsupported assumptions, select a smaller supported explanation. Notes should connect the preceding discussion to this task, including targeted help without presenting one mandatory student answer.
OPTIONAL LIMITS: default boundaryDecision to omit. Insert one limits page immediately before the final question ONLY when an actual wording, visual feature or inference makes a consequential misunderstanding likely. Record the specific trigger in boundaryReason. All analogies having limits or simply using physical objects is insufficient. A narrow source/receiver task alone does not require a tiny-material-objects warning. A private teacher follow-up if a misconception arises is often enough. If a limits slide is needed, pose one accessible question; keep the explanatory answer private. Omit or simplify a confusing boundary. Repair a faulty core analogy instead of compensating with a disclaimer.
FINAL question: ask learners to WRITE their OWN question about the SAME target, with room to record it. The app supplies a blank MY QUESTION card and general incomplete starters. Set body to an empty string: no teacher recap, 'Next, we will investigate...' transition, finished question or final answer on the student canvas. Put the brief bridge to the lesson in teacherNotes. This is page 6 by default, page 7 only with limits.
STRUCTURE AND REVISION: ordered stages are phenomenon, target, analogue, mapping, apply, optional limits, question. Exactly six pages when boundaryDecision=omit, seven when include. Exactly THREE image plans in order: phenomenon, target, analogue. No compulsory variation or controlled two-condition exercise. One central student action per page and stable names throughout. If feedback changes the target phenomenon, repair all affected target wording, plans, mapping, application, notes and final question, not just page 1. Preserve adequate content and unchanged image plans exactly when unaffected. All plan fields except the optional responseStarter are PRIVATE; mappingHint is an empty compatibility field and is never rendered in this method.`;

export const SIX_STEP_REVIEW_RULES = `SAMANEH SIX-STEP DEPENDENCY REVIEW — TEACHER-LED DISCUSSION:
Review the actual story, images and private facilitation against phenomenon -> target difficulty -> familiar activation -> teacher-led mapping -> application -> optional clarifying limits -> own question. Six pages without limits are complete. One useful relationship at one mapping depth is enough. Do not demand a variation image, controlled prediction, full lesson explanation or a perfect analogy.
AUTHENTICITY AND FIT: Page 1 must depict an authentic real-world TARGET phenomenon closely aligned with the specific lesson relationship and establish a context that leads naturally to page 2. The target may be unfamiliar and need not be from students' everyday lives. Never reject it solely for lack of personal experience or classroom location, and never accept it merely because objects are familiar. Compare targetPhenomenon/authenticityRationale with the actual scene, lesson relationship, and the literal background supplied to these learners. Flag unsupported invented facts, a lesson mismatch or missing context needed to understand the task. Evaluate its real-world basis and scientific relationship, not whether a learner has seen it. The chosen event must retain the intended scientific focus, not exchange stored-energy release for braking just because both mention energy. This flexibility concerns the TARGET: page 3 still needs a familiar, accessible analogue, not a second unexplained scientific system. Page 2 focuses on the hidden aspect of the SAME event; check stable object identities, contacts and mechanism. Neither early page introduces the familiar source. A visible illustrated before/after is allowed when planned; one frame cannot establish an unseen change. Cross-check release/contact wording against each frame: a held-before-release moment must not be described as after release. No solved arrows, invented internal mechanism or unavailable video.
STUDENT-FACING LANGUAGE: Titles must address learners through a recognizable situation or accessible question, not an instructional purpose. Flag unnecessary 'Familiar situation'/'Science situation' labels in generated text. Blank body/captions are valid when the image and question suffice; never request filler. The app does not print mappingHint in six-step decks. Any retained legacy value is private compatibility data, not a public foothold.
TEACHER-LED MAPPING: Page 3 activates the familiar relation alone. Page 4 shows the pair and asks one focused comparison question with an optional incomplete responseStarter. Check title, body, task, captions and starter together: ALL supplied correspondences and explanatory statements on the mapping slide are defects, including one formerly allowed foothold or a paraphrase. Even 'A compressed spring stores energy and can transfer some while expanding' belongs in teacherNotes here. Request moving such content to notes and retaining a concrete question, rather than replacing it with another public hint. Both possible answers and scientific prerequisites are appropriate in PRIVATE notes. Do not report a missing student-visible foothold just because a teacher introduces the needed idea verbally; instead verify notes contain specific questions, possible correspondences and usable help. Flag a definite unsupported task when neither learner context, accessible evidence nor the planned facilitation supports it. Do not demand that private explanations be duplicated on the slide.
APPLICATION: Page 5 uses the preceding discussion for a tentative explanation OR supported prediction with a reason. It may refer to the class's proposed correspondence but should not print a completed mapping or the requested scientific explanation. Check applicationSupport against the actual question and teacher guidance; a plan asserting support is not sufficient. Accounting does not establish a mass-speed or force law. A generic question about how or why motion starts overreaches a source/receiver comparison; narrow it explicitly to an energy source, receiver or distribution unless the plan establishes the needed mechanism. Prefer a smaller supported response over an ungrounded inference.
BOUNDARY AND QUESTION: Include limits only for a concrete likely misunderstanding invited by this actual mapping; general imperfection or physical objects alone are insufficient. A private follow-up may suffice. If present, the public boundary is a question, with its explanatory answer private. Final body is empty; the student's own question request, general starters and writing space are sufficient. Recaps and spoken lesson transitions belong in final teacherNotes. No completed question to copy. Inspect continuity after revision across all dependent fields.
Use exact quotes from EXISTING editable fields to report only definite failures, not hypothetical risks or optional polishing. An empty required teacher-guidance field cannot be quoted; quote the task whose support is missing and specify the needed facilitation. Keep scientifically correct private answers private, never treat their presence in notes as leakage.`;

export function analogyDesignRules(method?: AnalogyMethod) {
  if (resolveAnalogyMethod(method) === "six-step") return SIX_STEP_DESIGN_RULES;
  return resolveAnalogyMethod(method) === "reference-story" ? REFERENCE_STORY_DESIGN_RULES : ANALOGY_DESIGN_RULES;
}

export function analogyReviewRules(method?: AnalogyMethod) {
  if (resolveAnalogyMethod(method) === "six-step") return SIX_STEP_REVIEW_RULES;
  return resolveAnalogyMethod(method) === "reference-story" ? REFERENCE_STORY_REVIEW_RULES : ANALOGY_REVIEW_RULES;
}
import { resolveAnalogyMethod, type AnalogyMethod } from "./analogy-methods";
