/** Shared student/teacher separation; the two methods keep their own sequences. */
export const inquirySlideRules = `STUDENT INQUIRY AND PRIVATE TEACHER SUPPORT:
- Produce usable student-facing materials, not instructions to a teacher about materials to create. Use natural titles naming a concrete situation, detail or question; never print stage-purpose headings such as 'Present a Familiar Phenomenon', 'Discrepant Event' or 'Activate Prior Knowledge'. Do not number titles or prefix them with 'Slide 1' or '1.'; the app already numbers every page.
- Choose ONE lesson-aligned, scientifically defensible story. Keep its objects, action, conditions and time interval recognizable across pages. Put selection rationale and evidence status in private teacher notes. Simplify context without deleting the visible or remembered evidence students need to reason; do not substitute an unrelated decorative surprise.
- Each page has ONE concrete thinking action that builds on the previous page: a short reason or specific noticed detail may support that action. Use stable everyday names, state necessary setup before asking, and leave the requested inference to students. Essential results/data may be supplied as evidence when necessary, but then ask students to compare, interpret or identify a further pattern rather than copy the printed answer. Never withhold essential evidence merely to make a task seem open.
- Each page has a natural title (at most 10 words/64 characters), an OPTIONAL body UNDER 30 words/260 characters and at most two sentences, ONE task sentence (at most 24 words/180 characters), and two PRIVATE teacher notes of up to 150 words/900 characters each. A blank body or caption is preferable to filler when the scene and task suffice; keep necessary context, the required comparison entries and concept-recognition statement. Do not repeat the task in the body. Captions are optional literal scene names (at most 12 words/85 characters); alt text describes visible content (at most 30 words/160 characters).
- Private note 1 states the page's purpose, its link to this lesson and the reasoning to listen for; include why the experience/expectation is suitable and whether it is evidenced or provisional where relevant. Private note 2 gives a concrete discussion opener, possible responses, one non-leading follow-up if students are stuck, and a brief spoken transition. Possible answers are teacher preparation, not an explanation script to read before learners think. Keep facilitation, anticipated answers, recap and lesson bridge off the student canvas.
- The FINAL body MUST be empty. Students WRITE and hand in their OWN question they NOW want to investigate, not a fully written question to copy or an answer to the teacher's preceding question. Anchor the final task to the specific observation, remembered variation or unresolved comparison already encountered, while leaving what to ask open. Do not force every learner toward one prescribed question. The app supplies general incomplete starters and a blank MY QUESTION card, so do not repeat starters in generated text. In private notes the teacher briefly recalls the concrete unresolved observation, offers a noticing/changed-condition follow-up if needed without dictating a question, then collects questions and bridges verbally to the lesson without answering them.
- Pictures are instructional illustrations, not empirical measurements. Keep exact quantitative claims out unless explicitly supported; distinguish remembered, predicted and pictured events. No new experiment, unavailable media, causal diagram or completed explanation is needed. This is a class opening that creates curiosity, not the entire lesson.`;

export const inquiryReviewRules = `STUDENT INQUIRY REVIEW:
Inspect public titles, body, tasks, captions and alt separately from private teacher notes. A natural student title, optional short body or empty caption is valid; do not demand filler or generic stage headings. Teacher plans, possible answers, follow-up questions and spoken transitions belong in private notes and are not leakage there. Flag a definite teacher/writer instruction in a public field, or a task that simply repeats its supplied answer. Necessary evidence is allowed; do not remove an essential result when the task asks learners to interpret it rather than repeat it.
Check one coherent event/experience, stable object names and a clear time interval so the task follows from the prior page. A specific unresolved observation or variation must support the final learner question without prescribing a finished question or causal explanation. The final body is empty; the teacher briefly recalls the concrete unresolved observation in private notes. Students WRITE their own question they NOW want to investigate, not a fully written question to copy. Do not force every learner toward one prescribed question. The app provides incomplete starters and the blank question card.
Private notes should provide useful possible reasoning and a concrete, non-leading follow-up when the student task would otherwise lack support. Do not demand an exhaustive lesson script or treat a plausible learner response as an observed student belief. Report only definite defects with an exact quote and existing editable field; do not request optional stylistic polishing.
REVIEW OUTPUT: Use a SHORT verbatim quote of at most 80 characters from the selected field, ending at a word boundary. Select a shorter contiguous excerpt instead of truncating a long quote or adding ellipses, soft hyphens or invisible characters. Write problem and correction as concise COMPLETE sentences, aiming for at most 180 characters each; rewrite shorter rather than cutting a sentence off. Do not quote private guidance from a different field.`;
